# my_config.yaml
defaults:
  - encoder: small
  - decoder: small
  - vae: base
  - optimizer: base
  - losses: base
  - data: base

coordinates: absolute # or delta

hydra:
  job:
    env_set: 
      CUDA_VISIBLE_DEVICES: 6

wandb:
  project: MCG
  name: test1
  notes: This is a wandb hydra test