# my_config.yaml
defaults:
  - encoder: small
  - decoder: small
  - vae: base
  - optimizer: base
  - losses: base
  - data: base

coordinates: absolute # or delta

hydra:
  job:
    env_set: 
      CUDA_VISIBLE_DEVICES: 5
  run:
    dir: outputs/${wandb.name}_${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
      version: 1
      formatters:
        simple:
          format: '[%(filename)s] : [%(funcName)s] : %(message)s' #[%(levelname)s] : ...
      handlers:
        console:
          class: logging.StreamHandler
          formatter: simple
          level: INFO
          stream: ext://sys.stdout
      root:
        level: INFO
        handlers: [console, file]
        propagate: no

wandb:
  project: MCG
  name: aligned_backwards_test
  notes: Instead of taking a look at each independent subgraph as it is being generated and taking an aligned loss on that, I am focussing on aligning what has been built up so far and masking out the prev to prevent over focus.